<?php

namespace App\Http\Controllers;

use GuzzleHttp\Cookie\CookieJar;
use Illuminate\Http\Request;
use Symfony\Component\DomCrawler\Crawler;
use GuzzleHttp\Client;
use App\DailyStatusPortal;


class DailyStatusPortalController extends Controller
{
//    private $user = 'XRU9210097';
    private $user = 'rus9211689';
//    private $password = 'Qazxsw123+';
    private $password = 'Cc123123*';

// без испульзования VueJS
//    public function index()
//    {
//        $allProblemCiteArr['portal'] = $this->controlData();
//        return view('portal.daily-status-portal.daily-status-portal',  $allProblemCiteArr);
//    }
    public function apiClassic()
    {
        $DailyStatusPortal = new DailyStatusPortal();
        // получаеем данные в виде массивов СИТЫ, КЛИНТЫ, ТО ЗА ПЕРИОД
        $classicHtml = $this->PortalClassicParseHtml();
        //  выводим массив где ключ магазин, значение данные по магазину
        $allCiteClassicArr = $DailyStatusPortal->processingData($classicHtml);
        // оставляем только проблемыне и закрытые ситы
        $allProblemCiteArr['classic'] = $DailyStatusPortal->processingProblemData($allCiteClassicArr);

        return collect($allProblemCiteArr);
    }

    public function apiAtak()
    {
        $DailyStatusPortal = new DailyStatusPortal();
        // получаеем данные в виде массивов СИТЫ, КЛИНТЫ, ТО ЗА ПЕРИОД
        $atakHtml = $this->PortalAtakParseHtml();
        //  выводим массив где ключ магазин, значение данные по магазину
        $allCiteAtakArr = $DailyStatusPortal->processingData($atakHtml);
        // оставляем только проблемыне и закрытые ситы
        $allProblemCiteArr['atak'] = $DailyStatusPortal->processingProblemData($allCiteAtakArr);

        return collect($allProblemCiteArr);
    }

    /*
     * Упарвляющая функция
     */
    // без испульзования VueJS
//    public function controlData()
//    {
//        $DailyStatusPortal = new DailyStatusPortal();
//        // получаеем данные в виде массивов СИТЫ, КЛИНТЫ, ТО ЗА ПЕРИОД
//        $classicHtml = $this->PortalClassicParseHtml();
//        $atakHtml = $this->PortalAtakParseHtml();
//
//        //  выводим массив где ключ магазин, значение данные по магазину
//        $allCiteClassicArr = $DailyStatusPortal->processingData($classicHtml);
//        $allCiteAtakArr = $DailyStatusPortal->processingData($atakHtml);
//
//        // оставляем только проблемыне и закрытые ситы
//        $allProblemCiteArr['Classic'] = $DailyStatusPortal->processingProblemData($allCiteClassicArr);
//        $allProblemCiteArr['Atak'] = $DailyStatusPortal->processingProblemData($allCiteAtakArr);
//
//        return $allProblemCiteArr;
//
//        // временная разметка таблицей
////        echo '<div style="display: inline-flex">';
////        foreach ($allProblemCiteArr as $portalName => $portalData) {
////            echo '<div style="margin-right: 40px"><h3>' . $portalName . '</h3><table border="2">';
////            foreach ($portalData as $citeNme => $status) {
////                echo '<tr><td>' . $citeNme . '</td><td>' . $status . '</td></tr>';
////            }
////            echo '</table></div>';
////        }
////        echo '</div>';
//    }


    /*
     *  Получаем значение нужных нам полей из таблицы
     */
    public function PortalClassicParseHtml()
    {
        $PortalClassicHtmlParse = [
            // страница с контентом после авторизации
            'link' => 'http://w7ru09990004/daily-status-portal/portal-classic',
            // классы по которым парсим контент
            'citeNameClassParse' => '371',
            'clientsValueClassParse' => '375',
            'articleValueClassParse' => '383',
            'CaValueClassParse' => '403',
            'CaPeriodValueClassParse' => '415',
        ];
        $DailyStatusPortal = new DailyStatusPortal();
        $dataPortal = $DailyStatusPortal->getDataInPortal($PortalClassicHtmlParse);
        return $dataPortal;
    }


    /*
     *  Получаем значение нужных нам полей из таблицы
     */
    public function PortalAtakParseHtml()
    {
        $PortalAtakHtmlParse = [
            // страница с контентом после авторизации
            'link' => 'http://w7ru09990004/daily-status-portal/portal-atak',
            // классы по которым парсим контент
            'citeNameClassParse' => '336',
            'clientsValueClassParse' => '368',
            'articleValueClassParse' => '376',
            'CaValueClassParse' => '340',
            'CaPeriodValueClassParse' => '352',
        ];
        $DailyStatusPortal = new DailyStatusPortal();
        $dataPortal = $DailyStatusPortal->getDataInPortal($PortalAtakHtmlParse);
        return $dataPortal;
    }


    /*
     * Получаем Portal Classic в виде HTML страницы
     */
    public function getPortalClassicHtml()
    {
        $PortalClassicHtmlGetAuth = [
            // ссылка на базовую страницу
            'link' => 'http://portal.ru.auchan.com/portal/',
            // токены
            'tokenViewsState' => '/wEPDwUJMzgzMzg4MjUwD2QWAgIDD2QWCmYPDxYCHgRUZXh0BQrQm9C+0LPQuNC9ZGQCAg8PFgIfAAUM0J/QsNGA0L7Qu9GMZGQCBA8PFgIfAAUI0K/Qt9GL0LpkZAIFDxBkZBYBZmQCBg8WAh4FdmFsdWUFCNCS0YXQvtC0ZGQniGTj7tOUIsgb60FVI4XE91+HLQ==',
            'tokenEvanValidation' => '/wEWCQKAufxaAq+m6rYIAvK94JEPAvn6+RsCyYGW8wICjo+S1wQCgtyHhgwC7c2/agL6r+qNDFf2caYpL6FwNpwNbTiwK+9t04HV',
        ];
        // передаем данные для получения в функция для получения отчёта
        $xml = $this->getAuthAndReport($PortalClassicHtmlGetAuth);
        return $xml;
    }


    /*
     * Получаем Portal АТАК в виде HTML страницы
     */
    public function getPortalAtakHtml()
    {
        $PortalAtakHtmlGetAuth = [
            // ссылка на базовую страницу
            'link' => 'http://146.240.224.178/Portal/',
            // токены
            'tokenViewsState' => '/wEPDwUKMTg2MTIxMjgxMQ9kFgICAw9kFg5mDw8WAh4EVGV4dAUK0JvQvtCz0LjQvWRkAgIPDxYCHwAFDNCf0LDRgNC+0LvRjGRkAgMPD2QWAh4Kb25rZXlwcmVzcwUmcmV0dXJuIGNvbnRyb2xFbnRlcignYnRuRW50ZXInLCBldmVudClkAgQPDxYCHwAFCNCv0LfRi9C6ZGQCCg8QZBAVBQ7QoNGD0YHRgdC60LjQuQdFbmdsaXNoCUZyYW7Dp2FpcwhSb21hbmlhbhTQo9C60YDQsMOv0L3RgdGM0LrQsBUFBXJ1LVJVBWVuLVVTBWZyLUZSBXJvLVJPBXVrLVVBFCsDBWdnZ2dnFgFmZAILDw8WAh8ABQjQktGF0L7QtGRkAgwPDxYCHwAFKNCd0LXQstC10YDQvdGL0Lkg0LvQvtCz0LjQvS/Qv9Cw0YDQvtC70YxkZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WBQUJaW1nUnVzc2lhBQVpbWdVSwUJaW1nRnJhbmNlBQppbWdSb21hbmlhBQppbWdVa3JhaW5lId0ULP2sBh99ZTUPCbLcHHDzsz4=',
            'tokenEvanValidation' => '/wEWEQKc+Jw0Aq+m6rYIAvK94JEPArjo2tYOAo/JydQDAt6ZlIcMAoSA8r8NAoWB7pcKAvn6+RsCyYGW8wIC5Iz21QgCjo+S1wQC74G+xQICwoHiyggCl7fA+AEC7c2/agL6r+qNDIiMhxLvRMZeiUpVPXlMCzJNNHnK',
        ];
        // передаем данные для получения в функция для получения отчёта
        $xml = $this->getAuthAndReport($PortalAtakHtmlGetAuth);
        return $xml;
    }

    public function getAdminPortalClassicHtml()
    {
        $PortalAtakHtmlGetAuth = [
            // ссылка на базовую страницу
            'link' => 'http://portal.ru.auchan.com/iradmin2/',
            // токены
            'tokenViewsState' => '/wEPDwULLTE1MzMwNjI5MzBkZOqagiYgAo4JMe9TN957wRcBVGHK',
            'tokenEvanValidation' => '/wEWAwL08PbTAQKvpuq2CALyveCRD6VWgHb/gFTNuHcb5oYkLK82suC8',
        ];
        // передаем данные для получения в функция для получения отчёта
        $xml = $this->getPortalAdminAuth($PortalAtakHtmlGetAuth);
        return $xml;
    }


    /*
     *  Авторизация и получение всего HTML
     */
    public function getAuthAndReport($PortalHtmlGetAuth)
    {
        $client = new Client([
            // Base URI is used with relative requests
            'base_uri' => $PortalHtmlGetAuth['link'],
            // You can set any number of default request options.
            'timeout' => 60.0,
        ]);
        $cookieJar = new CookieJar();

        $client->request('POST', 'Login.aspx', [
                'form_params' => [
                    '__EVENTTARGET' => '',
                    '__EVENTARGUMENT' => '',
                    '__LASTFOCUS' => '',
                    '__VIEWSTATE' => $PortalHtmlGetAuth['tokenViewsState'],
                    '__EVENTVALIDATION' => $PortalHtmlGetAuth['tokenEvanValidation'],
                    'username' => $this->user,
                    'password' => $this->password,
                    'ddlLanguage' => 'ru-RU',
                    'btnLogin' => 'Вход',
                    'btnEnter' => 'Вход',
                    'hidscreenWidth' => '',
                    'hidscreenHeight' => '',
                ],
                'cookies' => $cookieJar,
                'headers' => [
                    'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36',
                ]
            ]
        );

        $response = $client->get('pg412100.aspx', ['cookies' => $cookieJar]);
        $xml = $response->getBody()->getContents();
        return $xml;
    }

    /*
     * Авторизация и получение всего HTML Портала Админ
     */
    public function getPortalAdminAuth($PortalHtmlGetAuth)
    {
        $client = new Client([
            // Base URI is used with relative requests
            'base_uri' => $PortalHtmlGetAuth['link'],
            // You can set any number of default request options.
            'timeout' => 60.0,
        ]);
        $cookieJar = new CookieJar();

        $client->request('POST', 'login.aspx', [
                'form_params' => [
                    '__VIEWSTATE' => $PortalHtmlGetAuth['tokenViewsState'],
                    '__EVENTVALIDATION' => $PortalHtmlGetAuth['tokenEvanValidation'],
                    'username' => $this->user,
                    'password' => $this->password,
                ],
                'cookies' => $cookieJar,
                'headers' => [
                    'User-Agent' => 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36',
                ]
            ]
        );

        $response1 = $client->get('ADRequest/Requests.aspx', ['cookies' => $cookieJar]);

//        $response2 = $client->request('POST', 'ADRequest/Requests.aspx',
//            [
//                'form_params' => [
//                    '__EVENTTARGET' => '',
//                    '__EVENTARGUMENT' => '',
//                    '__LASTFOCUS' => '',
//                    '__VIEWSTATE' => '/wEPDwUJMTUzOTUyMzkyD2QWAgIDD2QWDgIDDxBkZBYBZmQCCQ8QDxYCHgtfIURhdGFCb3VuZGdkEBUKBtCS0YHQtQJCSQhXb3JrZmxvdy3QkNC00LzQuNC90LjRgdGC0YDQsNGC0LjQstC90YvQtSDQt9Cw0LTQsNGH0Lgj0JjQvNC/0L7RgNGCINC00LDQvdC90YvRhSAtIGV4YWRhdGEK0J7RgtGH0LXRgivQn9C+0LTQs9C+0YLQvtCy0LrQsCDQstC40YLRgNC40L0gLSBleGFkYXRhStCh0YLQsNGA0YvQtSDQvdC10LjRgdC/0L7Qu9GM0LfRg9C10LzRi9C1INC+0L/QtdGA0LDRhtC40Lgg0LIg0LDRgNGF0LjQstC1HdCi0LXRgdGC0L7QstGL0LUg0LfQsNC00LDRh9C4G9Ct0LrRgdC/0L7RgNGCINC00LDQvdC90YvRhRUKBtCS0YHQtQIxMAE5ATQBMwExATIBMAE1ATYUKwMKZ2dnZ2dnZ2dnZxYBAgZkAg8PEA8WAh8AZ2QQFSMG0JLRgdC1GkJJIC0gUmVidWlsZCBBQ19NQVJUX0RNX0FDGkRhdGFtYXJ0IElORk9MT0cgRUdBSVMgREFZE0RhdGFtYXJ0IExvc3NlcyBPREkSRGF0YW1hcnQgU2FsZXMgT0RJCUhSQkkgTG9hZFFMQVNUX09SREVSIC0g0JLQuNGC0YDQuNC90LAg0L/QviDQv9C+0YHQu9C10LTQvdC40Lwg0LfQsNC60LDQt9Cw0Lwg0LQuINCg0YPQv9GC0Y5OTWludGVrIC0g0J7QsdC90L7QstC70LXQvdC40LUg0YHQv9GA0LDQstC+0YfQvdC40LrQvtCyINCc0LjQvdGC0LXQuiAtINCf0YDQvtC0Tk1pbnRlayAtINCe0LHQvdC+0LLQu9C10L3QuNC1INGB0L/RgNCw0LLQvtGH0L3QuNC60L7QsiDQnNC40L3RgtC10LogLSDQotC10YHRghRQZXJtYW5lbnQgT3JkZXJzIENSQzdSdXB0dXJlIC0g0J7QsdC90L7QstC70LXQvdC40LUg0YHQv9GA0LDQstC+0YfQvdC40LrQvtCyKdCS0LjRgtGA0LjQvdCwIFNQRUUgLSDQl9Cw0LPRgNGD0LfQutCwIEFXK9CS0LjRgtGA0LjQvdCwIFNQRUUgLSDQl9Cw0LPRgNGD0LfQutCwIFFWRE0v0JLQuNGC0YDQuNC90LAgU1BFRSAtINCX0LDQs9GA0YPQt9C60LAgU1Qg0LggQ08u0JLQuNGC0YDQuNC90LAg0JDRgdGB0L7RgNGC0LjQvNC10L3RgiAtIEVYQURXSDXQktC40YLRgNC40L3QsCDQkdGO0LTQttC10YLRiyDQsi4yLiBIeXBlcmlvbiAtIEVYQURXSCTQktC40YLRgNC40L3QsCDQl9Cw0L/QsNGB0YsgLSBFWEFEV0hP0JLQuNGC0YDQuNC90LAg0JfQsNC/0LDRgdGLINGBINGD0YfQtdGC0L7QvCDQvtCx0LXRgdGG0LXQvdC40LLQsNC90LjRjyAtIEVYQURXSDDQktC40YLRgNC40L3QsCDQl9Cw0L/QsNGB0YssINCa0YPQsSBBVy4gLSBFWEFEV0hP0JLQuNGC0YDQuNC90LAg0JfQsNC/0LDRgdGLLiDQl9Cw0L/QvtC70L3QtdC90LjQtSDQv9C+0YLQtdGA0Y/QvdC90YvRhSDQtNC90LXQuSrQktC40YLRgNC40L3QsCDQmNC30LzQtdGA0LXQvdC40Y8gLSBFWEFEV0go0JLQuNGC0YDQuNC90LAg0JjQvdGE0LvRj9GG0LjRjyAtIEVYQURXSCrQktC40YLRgNC40L3QsCDQmtC+0L3RgtGA0L7Qu9GPINC80LDRgNC20Lgq0JLQuNGC0YDQuNC90LAg0JzQvtC90LjRgtC+0YDQuNC90LMg0KbQtdC9H9CS0LjRgtGA0LjQvdCwINCf0YDQtdC80LDRgNC20LhI0JLQuNGC0YDQuNC90LAg0J/RgNC10LzQsNGA0LbQuCAtINC30LDQs9GA0YPQt9C60LAg0LTQsNC90L3Ri9GFIE9yYWNsZUdMS9CS0LjRgtGA0LjQvdCwINCf0YDQtdC80LDRgNC20LggLSDQt9Cw0LPRgNGD0LfQutCwINGB0L/RgNCw0LLQvtGH0L3QuNC60L7QsibQktC40YLRgNC40L3QsCDQn9GA0L7QtNCw0LbQuCAtIEVYQURXSDXQktC40YLRgNC40L3QsCDQodC/0LjRgdCw0L3QuNGPL9Cf0L7RgtC10YDQuCAtIEVYQURXSFfQktC40YLRgNC40L3QsCDQodC/0LjRgdCw0L3QuNGPL9Cf0L7RgtC10YDQuC4g0J/QtdGA0LXQt9Cw0LPRgNGD0LfQutCwINCz0L7QtNCwLiAtIEVYQUQl0JLQuNGC0YDQuNC90LAg0KHQv9GA0LDQstC+0YfQvdC40LrQuDPQktC40YLRgNC40L3QsCDQotCw0YDQuNGE0Ysg0LfQsNC60YPQv9C60LggLSBFWEFEV0gb0JLQuNGC0YDQuNC90LAg0KjRgtGA0LDRhNGLJtCX0LDQs9GA0YPQt9C60LAg0LLQuNGC0YDQuNC90YsgRE1fU1VQN9CX0LDQv9GD0YHQuiDQtdC20LXQtNC90LXQstC90YvRhSDQstC40YLRgNC40L0gLSBFWEFEV0gVIwItMQkyMjMxMzc1MjgJMjEwMDM5MjQ1CTIyMjY5NTQ5MQkyMjI2OTc0MDcJMTI5ODkyMzgwCTIwMDEwNDc0OAkxOTIyMTQ2MjAJMTkyMDU5NTI0CTE5MTg5MDMyOQkxOTE0NTYyNzkJMTI5ODkyMzc5CTEyOTg5MjM3OAYxMjAwMjgJMTE1MzA1NTAzCTExNTMwNTUwMQg3NTk4MDIxNAkxMTUzMDU1MDcJMTE1MzA1NTA2CDc1OTgwMjA0CDExODEwNzAxCTExNTMwNTUwMgkxMDcxNjIzNDkFNDc3MjQJMjEwMDM5MjQ2CTIxMTQxMTE4NAkyMTE0MTExODUJMTE1MzA1NTAwCTExNTMwNTUwNAkxMTUzMDU1MDUINzU5ODAyMDgINTAyNDYyMTkJMTA0OTIxNjAwCTEyOTg5MjM4Mgg3MTIyMzI1MBQrAyNnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2RkAhcPEGQQFQIG0JLRgdC1ByDQktGB0LUVAgItMQItMRQrAwJnZ2RkAhsPDxYEHgRUZXh0BQEqHgdUb29sVGlwBdsBIDA9MCAgYW5kIFJFUVVFU1RfREFURV9TVUJNSVRFRCBiZXR3ZWVuIHRvX2RhdGUoJzIxLjAxLjIwMTggMTg6MDAnLCdkZC5tbS55eXl5IEhIMjQ6TUknKSBhbmQgdG9fZGF0ZSgnMjIuMDEuMjAxOCAyMzo1OScsJ2RkLm1tLnl5eXkgSEgyNDpNSScpICBhbmQgcmVxdWVzdF9vcHJfdHlwZSA9IDIvbi9yIHNxbCB0aW1lIG1zID0gOTMsNzUvbi9yICsgYmlsZHQgdGltZSBtcyA9IDkzLDc1ZGQCIQ8QDxYCHwBnZBAVEQbQktGB0LUXRVhFeHRyYW5ldFRhc2tQcm9jUHJvZDEXRVhFeHRyYW5ldFRhc2tQcm9jUHJvZDIXRVhFeHRyYW5ldFRhc2tQcm9jUHJvZDMXRVhFeHRyYW5ldFRhc2tQcm9jUHJvZDQSRVhYTFNUYXNrUHJvY1Byb2QxEkVYWExTVGFza1Byb2NQcm9kMhJFWFhMU1Rhc2tQcm9jUHJvZDMSRVhYTFNUYXNrUHJvY1Byb2Q0EkVYWExTVGFza1Byb2NQcm9kNRJFWFhMU1Rhc2tQcm9jVGVzdDEOSVJUYXNrc1Byb2NXZWINSVJUYXNrc1Byb2NfMQ1JUlRhc2tzUHJvY18yD0lSWExTVGFza3NQcm9jMQ9JUlhMU1Rhc2tzUHJvYzMPSVJYTFNUYXNrc1Byb2M3FREAF0VYRXh0cmFuZXRUYXNrUHJvY1Byb2QxF0VYRXh0cmFuZXRUYXNrUHJvY1Byb2QyF0VYRXh0cmFuZXRUYXNrUHJvY1Byb2QzF0VYRXh0cmFuZXRUYXNrUHJvY1Byb2Q0EkVYWExTVGFza1Byb2NQcm9kMRJFWFhMU1Rhc2tQcm9jUHJvZDISRVhYTFNUYXNrUHJvY1Byb2QzEkVYWExTVGFza1Byb2NQcm9kNBJFWFhMU1Rhc2tQcm9jUHJvZDUSRVhYTFNUYXNrUHJvY1Rlc3QxDklSVGFza3NQcm9jV2ViDUlSVGFza3NQcm9jXzENSVJUYXNrc1Byb2NfMg9JUlhMU1Rhc2tzUHJvYzEPSVJYTFNUYXNrc1Byb2MzD0lSWExTVGFza3NQcm9jNxQrAxFnZ2dnZ2dnZ2dnZ2dnZ2dnZ2RkAisPPCsACwEADxYKHglQYWdlQ291bnQCAR4QQ3VycmVudFBhZ2VJbmRleGYeC18hSXRlbUNvdW50AhIeCERhdGFLZXlzFgAeFV8hRGF0YVNvdXJjZUl0ZW1Db3VudAISZBYCZg9kFiQCAg9kFiJmD2QWAgIBDw8WAh8BBQc3MjkyMzA1ZGQCAQ8PFgIfAQUSMjIuMDEuMjAxOCA3OjIwOjAzZGQCAg9kFgQCAQ8PFgIfAQUaQkkgLSBSZWJ1aWxkIEFDX01BUlRfRE1fQUNkZAIDD2QWAmYPFQEaQkkgLSBSZWJ1aWxkIEFDX01BUlRfRE1fQUNkAgMPDxYIHwEFFtCS0YvQv9C+0LvQvdGP0LXRgtGB0Y8fAgUNSVJUYXNrc1Byb2NfMh4JRm9yZUNvbG9yCmAeBF8hU0ICBGRkAgQPDxYEHglCYWNrQ29sb3IJyP/I/x8JAghkFgICAQ8PFgIfAQUU0J3QvtGA0LzQsNC70YzQvdGL0LlkZAIFD2QWAgIBDw8WAh8BBSZTQ0VOX05BTUU6IEJJX0RNX0FDX01BUlRfUkVCVUlMRF9ETV9BQ2RkAgYPZBYCAgEPD2QWAh4Hb25DbGljawU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRIyMi4wMS4yMDE4IDc6MjA6MDNkZAIJDw8WAh8BBQowMS4wMS4wMDAxZGQCCg8PFgIfAQUJMjA3NjI4NDM5ZGQCCw8PFgIfAQUJMjIzMTM3NTI4ZGQCDA8PFgIfAQUBMmRkAg0PDxYCHwEFCjIyLjAxLjIwMThkZAIODw8WAh8BBQ1BQ19NQVJUX0RNX0FDZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAgMPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MjA2N2RkAgEPDxYCHwEFEjIyLjAxLjIwMTggNzowMDowMGRkAgIPZBYEAgEPDxYCHwEFMdCg0LDRgdGH0LXRgiDQv9GA0LDQstC40Lsg0LrQvtC90YLRgNC+0LvRjyDRhtC10L1kZAIDD2QWAmYPFQEx0KDQsNGB0YfQtdGCINC/0YDQsNCy0LjQuyDQutC+0L3RgtGA0L7Qu9GPINGG0LXQvWQCAw8PFggfAQUW0JLRi9C/0L7Qu9C90Y/QtdGC0YHRjx8CBQ1JUlRhc2tzUHJvY18yHwgKYB8JAgRkZAIEDw8WBB8KCcj/yP8fCQIIZBYCAgEPDxYCHwEFFNCd0L7RgNC80LDQu9GM0L3Ri9C5ZGQCBQ9kFgICAQ8PFgIfAQUgREFURV9COiAyMDE4MDEyMTsgVEhSRUFEX0NOVDogMjVkZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRIyMi4wMS4yMDE4IDc6MDA6MDBkZAIJDw8WAh8BBQowMS4wMS4wMDAxZGQCCg8PFgIfAQUIMTcyMDk2OTZkZAILDw8WAh8BBQkxMDcxNjIzNDlkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjIuMDEuMjAxOGRkAg4PDxYCHwEFDE1BUkdJTl9QUklDRWRkAg8PDxYCHwEFJGh0dHA6Ly8xNDYuMjQwLjIyNC4yNS9QdWJsaWNSZXBvcnRzL2RkAhAPDxYCHwEFDUlSVGFza3NQcm9jXzJkZAIRDw8WAh8BBSHQn9C+0LTQs9C+0YLQvtCy0LjRgtGMINGB0YDQsNC30YNkZAIED2QWImYPZBYCAgEPDxYCHwEFBzcyOTIwNzBkZAIBDw8WAh8BBRIyMi4wMS4yMDE4IDc6MDA6MDFkZAICD2QWBAIBDw8WAh8BBU5NaW50ZWsgLSDQntCx0L3QvtCy0LvQtdC90LjQtSDRgdC/0YDQsNCy0L7Rh9C90LjQutC+0LIg0JzQuNC90YLQtdC6IC0g0J/RgNC+0LRkZAIDD2QWAmYPFQFOTWludGVrIC0g0J7QsdC90L7QstC70LXQvdC40LUg0YHQv9GA0LDQstC+0YfQvdC40LrQvtCyINCc0LjQvdGC0LXQuiAtINCf0YDQvtC0ZAIDDw8WCB8BBRDQktGL0L/QvtC70L3QtdC9HwIFDUlSVGFza3NQcm9jXzIfCApPHwkCBGRkAgQPDxYEHwoJyP/I/x8JAghkFgICAQ8PFgIfAQUU0J3QvtGA0LzQsNC70YzQvdGL0LlkZAIFD2QWAgIBDw8WAh8BZWRkAgYPZBYCAgEPD2QWAh8LBT9yZXR1cm4gY29uZmlybSgn0J7RgtC80LXQvdC40YLRjCDRgtC10LrRg9GJ0LjQuSDQt9Cw0L/RgNC+0YE/JylkAggPDxYCHwEFEjIyLjAxLjIwMTggNzowMDowMWRkAgkPDxYCHwEFCjIyLjAxLjIwMThkZAIKDw8WAh8BBQgxNzIwOTY5NmRkAgsPDxYCHwEFCTE5MjIxNDYyMGRkAgwPDxYCHwEFATJkZAINDw8WAh8BBQoyMi4wMS4yMDE4ZGQCDg8PFgIfAQUXTUlOVEVLX0RJQ1RfVVBEQVRFX1BST0RkZAIPDw8WAh8BBSRodHRwOi8vMTQ2LjI0MC4yMjQuMjUvUHVibGljUmVwb3J0cy9kZAIQDw8WAh8BBQ1JUlRhc2tzUHJvY18yZGQCEQ8PFgIfAQUh0J/QvtC00LPQvtGC0L7QstC40YLRjCDRgdGA0LDQt9GDZGQCBQ9kFiJmD2QWAgIBDw8WAh8BBQc3MjkxODMzZGQCAQ8PFgIfAQUSMjIuMDEuMjAxOCA2OjMwOjAwZGQCAg9kFgQCAQ8PFgIfAQU3UnVwdHVyZSAtINCe0LHQvdC+0LLQu9C10L3QuNC1INGB0L/RgNCw0LLQvtGH0L3QuNC60L7QsmRkAgMPZBYCZg8VATdSdXB0dXJlIC0g0J7QsdC90L7QstC70LXQvdC40LUg0YHQv9GA0LDQstC+0YfQvdC40LrQvtCyZAIDDw8WCB8BBRDQktGL0L/QvtC70L3QtdC9HwIFDUlSVGFza3NQcm9jXzIfCApPHwkCBGRkAgQPDxYEHwoJyP/I/x8JAghkFgICAQ8PFgIfAQUU0J3QvtGA0LzQsNC70YzQvdGL0LlkZAIFD2QWAgIBDw8WAh8BBSJEQVRFX0I6IDIwMTgwMTE3OyBEQVRFX0U6IDIwMTgwMTIxZGQCBg9kFgICAQ8PZBYCHwsFP3JldHVybiBjb25maXJtKCfQntGC0LzQtdC90LjRgtGMINGC0LXQutGD0YnQuNC5INC30LDQv9GA0L7RgT8nKWQCCA8PFgIfAQUSMjIuMDEuMjAxOCA2OjMwOjAwZGQCCQ8PFgIfAQUKMjIuMDEuMjAxOGRkAgoPDxYCHwEFCDE3MjA5Njk2ZGQCCw8PFgIfAQUJMTkxNDU2Mjc5ZGQCDA8PFgIfAQUBMmRkAg0PDxYCHwEFCjIyLjAxLjIwMThkZAIODw8WAh8BBRNSVVBUVVJFX0RJQ1RfVVBEQVRFZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAgYPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTc2M2RkAgEPDxYCHwEFEjIyLjAxLjIwMTggNjowMDowM2RkAgIPZBYEAgEPDxYCHwEFTk1pbnRlayAtINCe0LHQvdC+0LLQu9C10L3QuNC1INGB0L/RgNCw0LLQvtGH0L3QuNC60L7QsiDQnNC40L3RgtC10LogLSDQotC10YHRgmRkAgMPZBYCZg8VAU5NaW50ZWsgLSDQntCx0L3QvtCy0LvQtdC90LjQtSDRgdC/0YDQsNCy0L7Rh9C90LjQutC+0LIg0JzQuNC90YLQtdC6IC0g0KLQtdGB0YJkAgMPDxYIHwEFENCS0YvQv9C+0LvQvdC10L0fAgUNSVJUYXNrc1Byb2NfMh8ICk8fCQIEZGQCBA8PFgQfCgnI/8j/HwkCCGQWAgIBDw8WAh8BBRTQndC+0YDQvNCw0LvRjNC90YvQuWRkAgUPZBYCAgEPDxYCHwFlZGQCBg9kFgICAQ8PZBYCHwsFP3JldHVybiBjb25maXJtKCfQntGC0LzQtdC90LjRgtGMINGC0LXQutGD0YnQuNC5INC30LDQv9GA0L7RgT8nKWQCCA8PFgIfAQUSMjIuMDEuMjAxOCA2OjAwOjAzZGQCCQ8PFgIfAQUKMjIuMDEuMjAxOGRkAgoPDxYCHwEFCDE3MjA5Njk2ZGQCCw8PFgIfAQUJMTkyMDU5NTI0ZGQCDA8PFgIfAQUBMmRkAg0PDxYCHwEFCjIyLjAxLjIwMThkZAIODw8WAh8BBRdNSU5URUtfRElDVF9VUERBVEVfVEVTVGRkAg8PDxYCHwEFJGh0dHA6Ly8xNDYuMjQwLjIyNC4yNS9QdWJsaWNSZXBvcnRzL2RkAhAPDxYCHwEFDUlSVGFza3NQcm9jXzJkZAIRDw8WAh8BBSHQn9C+0LTQs9C+0YLQvtCy0LjRgtGMINGB0YDQsNC30YNkZAIHD2QWImYPZBYCAgEPDxYCHwEFBzcyOTE3NTNkZAIBDw8WAh8BBRIyMi4wMS4yMDE4IDU6NTA6MDJkZAICD2QWBAIBDw8WBB8BBSTQktC40YLRgNC40L3QsCDQl9Cw0L/QsNGB0YsgLSBFWEFEV0geB1Zpc2libGVoZGQCAw8PFgQeC05hdmlnYXRlVXJsBRNOVkwoUkVRVUVTVF9VUkwsIC0pHwxnZBYCZg8VASTQktC40YLRgNC40L3QsCDQl9Cw0L/QsNGB0YsgLSBFWEFEV0hkAgMPDxYIHwEFENCS0YvQv9C+0LvQvdC10L0fAgUNSVJUYXNrc1Byb2NfMh8ICk8fCQIEZGQCBA8PFgQfCgnI/8j/HwkCCGQWAgIBDw8WAh8BBRTQndC+0YDQvNCw0LvRjNC90YvQuWRkAgUPZBYCAgEPDxYCHwEFFEJFR0lOX0RBVEU6IDIwMTgwMTIxZGQCBg9kFgICAQ8PZBYCHwsFP3JldHVybiBjb25maXJtKCfQntGC0LzQtdC90LjRgtGMINGC0LXQutGD0YnQuNC5INC30LDQv9GA0L7RgT8nKWQCCA8PFgIfAQUSMjIuMDEuMjAxOCA1OjUwOjAyZGQCCQ8PFgIfAQUKMjIuMDEuMjAxOGRkAgoPDxYCHwEFCDE3MjA5Njk2ZGQCCw8PFgIfAQUINzU5ODAyMTRkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjIuMDEuMjAxOGRkAg4PDxYCHwEFDlNUT0NLX01BUlRfRVhBZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAggPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTU4NmRkAgEPDxYCHwEFEjIyLjAxLjIwMTggNTowMDowNWRkAgIPZBYEAgEPDxYCHwEFJtCT0YDRg9C/0L/QvtCy0L7QuTogRGF0YW1hcnQgU2FsZXMgT0RJZGQCAw9kFgJmDxUBJtCT0YDRg9C/0L/QvtCy0L7QuTogRGF0YW1hcnQgU2FsZXMgT0RJZAIDDw8WCB8BBRDQktGL0L/QvtC70L3QtdC9HwIFDUlSVGFza3NQcm9jXzIfCApPHwkCBGRkAgQPDxYEHwoJyP/I/x8JAghkFgICAQ8PFgIfAQUU0J3QvtGA0LzQsNC70YzQvdGL0LlkZAIFD2QWAgIBDw8WAh8BBUhBVUNIQU4uQ0xFQVI6IDA7IEFVQ0hBTi5EQVRFX0I6IDIwMTgwMTIxOyBBVUNIQU4uREFURV9FOiAyMDE4MDEyMTsgQVUuLi5kZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRIyMi4wMS4yMDE4IDU6MDA6MDVkZAIJDw8WAh8BBQoyMi4wMS4yMDE4ZGQCCg8PFgIfAQUJMjA3NjI4NDM5ZGQCCw8PFgIfAQUJMjIyNjk3NDA3ZGQCDA8PFgIfAQUBMmRkAg0PDxYCHwEFCjIyLjAxLjIwMThkZAIODw8WAh8BBRBQT1JUQUwyX0NPTVBfT0RJZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAgkPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTU4NWRkAgEPDxYCHwEFEjIyLjAxLjIwMTggNTowMDowNGRkAgIPZBYEAgEPDxYCHwEFGkRhdGFtYXJ0IElORk9MT0cgRUdBSVMgREFZZGQCAw9kFgJmDxUBGkRhdGFtYXJ0IElORk9MT0cgRUdBSVMgREFZZAIDDw8WCB8BBRDQktGL0L/QvtC70L3QtdC9HwIFDUlSVGFza3NQcm9jXzIfCApPHwkCBGRkAgQPDxYEHwoJyP/I/x8JAghkFgICAQ8PFgIfAQUU0J3QvtGA0LzQsNC70YzQvdGL0LlkZAIFD2QWAgIBDw8WAh8BBUhBVUNIQU4uREFURV9COiAyMDE4MDEyMjsgQVVDSEFOLkRBVEVfRTogNDAwMDEyMzE7IEFVQ0hBTi5SSUQ6ICNSSUQjOyAuLi5kZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRIyMi4wMS4yMDE4IDU6MDA6MDRkZAIJDw8WAh8BBQoyMi4wMS4yMDE4ZGQCCg8PFgIfAQUIMTcyMDk2OTZkZAILDw8WAh8BBQkyMTAwMzkyNDVkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjIuMDEuMjAxOGRkAg4PDxYCHwEFFERNX0lORk9MT0dfRUdBSVNfREFZZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAgoPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTUzMGRkAgEPDxYCHwEFEjIyLjAxLjIwMTggNDoxNTowMWRkAgIPZBYEAgEPDxYEHwEFOtCT0YDRg9C/0L/QvtCy0L7QuTog0JLQuNGC0YDQuNC90LAg0J/RgNC+0LTQsNC20LggLSBFWEFEV0gfDGhkZAIDDw8WBB8NBRJOVkwoUkVRVUVTVF9VUkwsICkfDGdkFgJmDxUBOtCT0YDRg9C/0L/QvtCy0L7QuTog0JLQuNGC0YDQuNC90LAg0J/RgNC+0LTQsNC20LggLSBFWEFEV0hkAgMPDxYIHwEFENCS0YvQv9C+0LvQvdC10L0fAgUNSVJUYXNrc1Byb2NfMh8ICk8fCQIEZGQCBA8PFgQfCgnI/8j/HwkCCGQWAgIBDw8WAh8BBRTQndC+0YDQvNCw0LvRjNC90YvQuWRkAgUPZBYCAgEPDxYCHwEFSEJFR0lOX0RBVEU6IDIwMTgwMTIxOyBDTEVBUjogMDsgRU5EX0RBVEU6IDIwMTgwMTIxOyBSRUZfTE9BRF9ZRUFSOiBBVS4uLmRkAgYPZBYCAgEPD2QWAh8LBT9yZXR1cm4gY29uZmlybSgn0J7RgtC80LXQvdC40YLRjCDRgtC10LrRg9GJ0LjQuSDQt9Cw0L/RgNC+0YE/JylkAggPDxYCHwEFEjIyLjAxLjIwMTggNDoxNTowMWRkAgkPDxYCHwEFCjIyLjAxLjIwMThkZAIKDw8WAh8BBQUxMzkyOGRkAgsPDxYCHwEFCTExNTMwNTUwMGRkAgwPDxYCHwEFATJkZAINDw8WAh8BBQoyMi4wMS4yMDE4ZGQCDg8PFgIfAQUQUE9SVEFMMl9DT01QX0VYQWRkAg8PDxYCHwEFJGh0dHA6Ly8xNDYuMjQwLjIyNC4yNS9QdWJsaWNSZXBvcnRzL2RkAhAPDxYCHwEFDUlSVGFza3NQcm9jXzJkZAIRDw8WAh8BBSHQn9C+0LTQs9C+0YLQvtCy0LjRgtGMINGB0YDQsNC30YNkZAILD2QWImYPZBYCAgEPDxYCHwEFBzcyOTE0OTRkZAIBDw8WAh8BBRIyMi4wMS4yMDE4IDQ6MDA6MDZkZAICD2QWBAIBDw8WAh8BBRRQZXJtYW5lbnQgT3JkZXJzIENSQ2RkAgMPZBYCZg8VARRQZXJtYW5lbnQgT3JkZXJzIENSQ2QCAw8PFggfAQUQ0JLRi9C/0L7Qu9C90LXQvR8CBQ1JUlRhc2tzUHJvY18yHwgKTx8JAgRkZAIEDw8WBB8KCcj/yP8fCQIIZBYCAgEPDxYCHwEFFNCd0L7RgNC80LDQu9GM0L3Ri9C5ZGQCBQ9kFgICAQ8PFgIfAQU4QVVDSEFOLkRBVEVfRTogMjAxODAxMjI7IFNDRU5fTkFNRTogUEVSTUFORU5UX09SREVSU19DUkNkZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRIyMi4wMS4yMDE4IDQ6MDA6MDZkZAIJDw8WAh8BBQoyMi4wMS4yMDE4ZGQCCg8PFgIfAQUIOTEyMjc3MDRkZAILDw8WAh8BBQkxOTE4OTAzMjlkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjIuMDEuMjAxOGRkAg4PDxYCHwEFFFBFUk1BTkVOVF9PUkRFUlNfQ1JDZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAgwPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTQ2MGRkAgEPDxYCHwEFEjIyLjAxLjIwMTggMzo0NTowM2RkAgIPZBYEAgEPDxYCHwEFE0RhdGFtYXJ0IExvc3NlcyBPRElkZAIDD2QWAmYPFQETRGF0YW1hcnQgTG9zc2VzIE9ESWQCAw8PFggfAQUQ0JLRi9C/0L7Qu9C90LXQvR8CBQ1JUlRhc2tzUHJvY18yHwgKTx8JAgRkZAIEDw8WBB8KCcj/yP8fCQIIZBYCAgEPDxYCHwEFFNCd0L7RgNC80LDQu9GM0L3Ri9C5ZGQCBQ9kFgICAQ8PFgIfAQVIQVVDSEFOLkNMRUFSOiAwOyBBVUNIQU4uREFURV9COiAyMDE4MDEyMTsgQVVDSEFOLkRBVEVfRTogMjAxODAxMjE7IEFVLi4uZGQCBg9kFgICAQ8PZBYCHwsFP3JldHVybiBjb25maXJtKCfQntGC0LzQtdC90LjRgtGMINGC0LXQutGD0YnQuNC5INC30LDQv9GA0L7RgT8nKWQCCA8PFgIfAQUSMjIuMDEuMjAxOCAzOjQ1OjAzZGQCCQ8PFgIfAQUKMjIuMDEuMjAxOGRkAgoPDxYCHwEFCTIwNzYyODQzOWRkAgsPDxYCHwEFCTIyMjY5NTQ5MWRkAgwPDxYCHwEFATJkZAINDw8WAh8BBQoyMi4wMS4yMDE4ZGQCDg8PFgIfAQUPTE9TU0VTX01BUlRfT0RJZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAg0PZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTM3NWRkAgEPDxYCHwEFEjIyLjAxLjIwMTggMzoxMDowM2RkAgIPZBYEAgEPDxYEHwEFNdCS0LjRgtGA0LjQvdCwINCh0L/QuNGB0LDQvdC40Y8v0J/QvtGC0LXRgNC4IC0gRVhBRFdIHwxoZGQCAw8PFgQfDQUSTlZMKFJFUVVFU1RfVVJMLCApHwxnZBYCZg8VATXQktC40YLRgNC40L3QsCDQodC/0LjRgdCw0L3QuNGPL9Cf0L7RgtC10YDQuCAtIEVYQURXSGQCAw8PFggfAQUQ0JLRi9C/0L7Qu9C90LXQvR8CBQ1JUlRhc2tzUHJvY18yHwgKTx8JAgRkZAIEDw8WBB8KCcj/yP8fCQIIZBYCAgEPDxYCHwEFFNCd0L7RgNC80LDQu9GM0L3Ri9C5ZGQCBQ9kFgICAQ8PFgIfAQUyQkVHSU5fREFURTogMjAxODAxMjE7IENMRUFSOiAwOyBFTkRfREFURTogMjAxODAxMjFkZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRIyMi4wMS4yMDE4IDM6MTA6MDNkZAIJDw8WAh8BBQoyMi4wMS4yMDE4ZGQCCg8PFgIfAQUFMTM5MjhkZAILDw8WAh8BBQkxMTUzMDU1MDRkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjIuMDEuMjAxOGRkAg4PDxYCHwEFD0xPU1NFU19NQVJUX0VYQWRkAg8PDxYCHwEFJGh0dHA6Ly8xNDYuMjQwLjIyNC4yNS9QdWJsaWNSZXBvcnRzL2RkAhAPDxYCHwEFDUlSVGFza3NQcm9jXzJkZAIRDw8WAh8BBSHQn9C+0LTQs9C+0YLQvtCy0LjRgtGMINGB0YDQsNC30YNkZAIOD2QWImYPZBYCAgEPDxYCHwEFBzcyOTEyOTdkZAIBDw8WAh8BBRIyMi4wMS4yMDE4IDI6MzA6MDVkZAICD2QWBAIBDw8WBB8BBSTQktC40YLRgNC40L3QsCDQl9Cw0L/QsNGB0YsgLSBFWEFEV0gfDGhkZAIDDw8WBB8NBRNOVkwoUkVRVUVTVF9VUkwsIC0pHwxnZBYCZg8VASTQktC40YLRgNC40L3QsCDQl9Cw0L/QsNGB0YsgLSBFWEFEV0hkAgMPDxYIHwEFENCS0YvQv9C+0LvQvdC10L0fAgUNSVJUYXNrc1Byb2NfMh8ICk8fCQIEZGQCBA8PFgQfCgnI/8j/HwkCCGQWAgIBDw8WAh8BBRTQndC+0YDQvNCw0LvRjNC90YvQuWRkAgUPZBYCAgEPDxYCHwEFFEJFR0lOX0RBVEU6IDIwMTgwMTIxZGQCBg9kFgICAQ8PZBYCHwsFP3JldHVybiBjb25maXJtKCfQntGC0LzQtdC90LjRgtGMINGC0LXQutGD0YnQuNC5INC30LDQv9GA0L7RgT8nKWQCCA8PFgIfAQUSMjIuMDEuMjAxOCAyOjMwOjA1ZGQCCQ8PFgIfAQUKMjIuMDEuMjAxOGRkAgoPDxYCHwEFCDE3MjA5Njk2ZGQCCw8PFgIfAQUINzU5ODAyMTRkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjIuMDEuMjAxOGRkAg4PDxYCHwEFDlNUT0NLX01BUlRfRVhBZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAg8PZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTE0OWRkAgEPDxYCHwEFEjIyLjAxLjIwMTggMTowNTowMWRkAgIPZBYEAgEPDxYCHwEFEkRhdGFtYXJ0IFNhbGVzIE9ESWRkAgMPZBYCZg8VARJEYXRhbWFydCBTYWxlcyBPRElkAgMPDxYIHwEFENCS0YvQv9C+0LvQvdC10L0fAgUNSVJUYXNrc1Byb2NfMh8ICk8fCQIEZGQCBA8PFgQfCgnI/8j/HwkCCGQWAgIBDw8WAh8BBRTQndC+0YDQvNCw0LvRjNC90YvQuWRkAgUPZBYCAgEPDxYCHwEFSEFVQ0hBTi5DTEVBUjogMDsgQVVDSEFOLkRBVEVfQjogMjAxODAxMjE7IEFVQ0hBTi5EQVRFX0U6IDIwMTgwMTIxOyBBVS4uLmRkAgYPZBYCAgEPD2QWAh8LBT9yZXR1cm4gY29uZmlybSgn0J7RgtC80LXQvdC40YLRjCDRgtC10LrRg9GJ0LjQuSDQt9Cw0L/RgNC+0YE/JylkAggPDxYCHwEFEjIyLjAxLjIwMTggMTowNTowMWRkAgkPDxYCHwEFCjIyLjAxLjIwMThkZAIKDw8WAh8BBQg5MTIyNzcwNGRkAgsPDxYCHwEFCTIyMjY5NzQwN2RkAgwPDxYCHwEFATJkZAINDw8WAh8BBQoyMi4wMS4yMDE4ZGQCDg8PFgIfAQUQUE9SVEFMMl9DT01QX09ESWRkAg8PDxYCHwEFJGh0dHA6Ly8xNDYuMjQwLjIyNC4yNS9QdWJsaWNSZXBvcnRzL2RkAhAPDxYCHwEFDUlSVGFza3NQcm9jXzJkZAIRDw8WAh8BBSHQn9C+0LTQs9C+0YLQvtCy0LjRgtGMINGB0YDQsNC30YNkZAIQD2QWImYPZBYCAgEPDxYCHwEFBzcyOTExMDNkZAIBDw8WAh8BBRMyMS4wMS4yMDE4IDIzOjAwOjAzZGQCAg9kFgQCAQ8PFgQfAQUu0JLQuNGC0YDQuNC90LAg0JDRgdGB0L7RgNGC0LjQvNC10L3RgiAtIEVYQURXSB8MaGRkAgMPDxYEHw0FEk5WTChSRVFVRVNUX1VSTCwgKR8MZ2QWAmYPFQEu0JLQuNGC0YDQuNC90LAg0JDRgdGB0L7RgNGC0LjQvNC10L3RgiAtIEVYQURXSGQCAw8PFggfAQUQ0JLRi9C/0L7Qu9C90LXQvR8CBQ1JUlRhc2tzUHJvY18yHwgKTx8JAgRkZAIEDw8WBB8KCcj/yP8fCQIIZBYCAgEPDxYCHwEFFNCd0L7RgNC80LDQu9GM0L3Ri9C5ZGQCBQ9kFgICAQ8PFgIfAQUyQkVHSU5fREFURTogMjAxODAxMjA7IENMRUFSOiAxOyBFTkRfREFURTogMjAxODAxMjBkZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRMyMS4wMS4yMDE4IDIzOjAwOjAzZGQCCQ8PFgIfAQUKMjEuMDEuMjAxOGRkAgoPDxYCHwEFBTEzOTI4ZGQCCw8PFgIfAQUJMTE1MzA1NTAzZGQCDA8PFgIfAQUBMmRkAg0PDxYCHwEFCjIxLjAxLjIwMThkZAIODw8WAh8BBQ1BU1JUX01BUlRfRVhBZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAhEPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MTAyMGRkAgEPDxYCHwEFEzIxLjAxLjIwMTggMjE6MzA6MDRkZAICD2QWBAIBDw8WBB8BBSrQktC40YLRgNC40L3QsCDQnNC+0L3QuNGC0L7RgNC40L3QsyDQptC10L0fDGhkZAIDDw8WBB8NBRJOVkwoUkVRVUVTVF9VUkwsICkfDGdkFgJmDxUBKtCS0LjRgtGA0LjQvdCwINCc0L7QvdC40YLQvtGA0LjQvdCzINCm0LXQvWQCAw8PFggfAQUQ0JLRi9C/0L7Qu9C90LXQvR8CBQ1JUlRhc2tzUHJvY18yHwgKTx8JAgRkZAIEDw8WBB8KCcj/yP8fCQIIZBYCAgEPDxYCHwEFFNCd0L7RgNC80LDQu9GM0L3Ri9C5ZGQCBQ9kFgICAQ8PFgIfAWVkZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRMyMS4wMS4yMDE4IDIxOjMwOjA0ZGQCCQ8PFgIfAQUKMjEuMDEuMjAxOGRkAgoPDxYCHwEFBTEzOTI4ZGQCCw8PFgIfAQUFNDc3MjRkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjEuMDEuMjAxOGRkAg4PDxYCHwEFCEZjSW1wb3J0ZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkAhIPZBYiZg9kFgICAQ8PFgIfAQUHNzI5MDg3NmRkAgEPDxYCHwEFEzIxLjAxLjIwMTggMjA6MzU6MDBkZAICD2QWBAIBDw8WBB8BBSrQktC40YLRgNC40L3QsCDQmNC30LzQtdGA0LXQvdC40Y8gLSBFWEFEV0gfDGhkZAIDDw8WBB8NBRJOVkwoUkVRVUVTVF9VUkwsICkfDGdkFgJmDxUBKtCS0LjRgtGA0LjQvdCwINCY0LfQvNC10YDQtdC90LjRjyAtIEVYQURXSGQCAw8PFggfAQUQ0JLRi9C/0L7Qu9C90LXQvR8CBQ1JUlRhc2tzUHJvY18yHwgKTx8JAgRkZAIEDw8WBB8KCcj/yP8fCQIIZBYCAgEPDxYCHwEFFNCd0L7RgNC80LDQu9GM0L3Ri9C5ZGQCBQ9kFgICAQ8PFgIfAWVkZAIGD2QWAgIBDw9kFgIfCwU/cmV0dXJuIGNvbmZpcm0oJ9Ce0YLQvNC10L3QuNGC0Ywg0YLQtdC60YPRidC40Lkg0LfQsNC/0YDQvtGBPycpZAIIDw8WAh8BBRMyMS4wMS4yMDE4IDIwOjM1OjAwZGQCCQ8PFgIfAQUKMjEuMDEuMjAxOGRkAgoPDxYCHwEFBTEzOTI4ZGQCCw8PFgIfAQUIMTE4MTA3MDFkZAIMDw8WAh8BBQEyZGQCDQ8PFgIfAQUKMjEuMDEuMjAxOGRkAg4PDxYCHwEFD1BPUlRBTDJfRElNX0VYQWRkAg8PDxYCHwEFJGh0dHA6Ly8xNDYuMjQwLjIyNC4yNS9QdWJsaWNSZXBvcnRzL2RkAhAPDxYCHwEFDUlSVGFza3NQcm9jXzJkZAIRDw8WAh8BBSHQn9C+0LTQs9C+0YLQvtCy0LjRgtGMINGB0YDQsNC30YNkZAITD2QWImYPZBYCAgEPDxYCHwEFBzcyOTA3MDJkZAIBDw8WAh8BBRMyMS4wMS4yMDE4IDE5OjMwOjAzZGQCAg9kFgQCAQ8PFgQfAQUl0JLQuNGC0YDQuNC90LAg0KHQv9GA0LDQstC+0YfQvdC40LrQuB8MaGRkAgMPDxYEHw0FE05WTChSRVFVRVNUX1VSTCwgLSkfDGdkFgJmDxUBJdCS0LjRgtGA0LjQvdCwINCh0L/RgNCw0LLQvtGH0L3QuNC60LhkAgMPDxYIHwEFENCS0YvQv9C+0LvQvdC10L0fAgUNSVJUYXNrc1Byb2NfMh8ICk8fCQIEZGQCBA8PFgQfCgnI/8j/HwkCCGQWAgIBDw8WAh8BBRTQndC+0YDQvNCw0LvRjNC90YvQuWRkAgUPZBYCAgEPDxYCHwFlZGQCBg9kFgICAQ8PZBYCHwsFP3JldHVybiBjb25maXJtKCfQntGC0LzQtdC90LjRgtGMINGC0LXQutGD0YnQuNC5INC30LDQv9GA0L7RgT8nKWQCCA8PFgIfAQUTMjEuMDEuMjAxOCAxOTozMDowM2RkAgkPDxYCHwEFCjIxLjAxLjIwMThkZAIKDw8WAh8BBQgxNzIwOTY5NmRkAgsPDxYCHwEFCDc1OTgwMjA4ZGQCDA8PFgIfAQUBMmRkAg0PDxYCHwEFCjIxLjAxLjIwMThkZAIODw8WAh8BBQdXSDJXV0hIZGQCDw8PFgIfAQUkaHR0cDovLzE0Ni4yNDAuMjI0LjI1L1B1YmxpY1JlcG9ydHMvZGQCEA8PFgIfAQUNSVJUYXNrc1Byb2NfMmRkAhEPDxYCHwEFIdCf0L7QtNCz0L7RgtC+0LLQuNGC0Ywg0YHRgNCw0LfRg2RkZO/3uvcMqNRu9Bu9goDXJ9o59Ke5',
//                    '__EVENTVALIDATION' => '/wEWmgECroq6ugQCn9i2hgcCnLec6AsC8PHP6gECnLec6AsC7JunogsC9eqF8g4C+IPr6QwCj/jmrwMCwPTO2gQCgJeMwg8CmJfMwQ8Cg5fMwQ8CgpfMwQ8CgJfMwQ8CgZfMwQ8Cn5fMwQ8ChJfMwQ8ChZfMwQ8CyNCZig4C29DViQ4CxNDViQ4CxdDViQ4CxtDViQ4Cx9DViQ4CwNDViQ4CwdDViQ4ChIXaygoCqNO27QYC073r3ggCoOfQ9g8CgpuF2AMCiJu52AwCns+nnQICmdbJvwYCoKnlhgYCw5bLkAQCnfCCmQMC/oqM1wEClc+j/AwCls+j/AwCuqiQngECoIDf/QoCooDf/QoCpJvT/wgCpIDf/QoCu4Df/QoCgazxlAcCnvORlQoCp4Df/QoCzO6K8AMChs/k9goCpefQ9g8Cj7vSlA4CiLvSlA4CoYDf/QoCpYDf/QoCpoDf/QoCgazB2g8C64y6SwLdrKKADQKYz6edAgKgt+PyBwLHiK64DwLi8POYBgL98POYBgLfpNiTAQLVrKjbBwKqua+/BQKqua+/BQKN3ogVAoqZ7RMCp8mo2wsCoobHTQKG+9eNCwLO0c2ECwKQ9vDPCALhstuPCQLaq7XxDAKr5J+xDQKdg8mSDwKdg82SDwKdg7GRDwKdg7WRDwKdg7mRDwL41Ny9CgK/tLbVCgLTtJ5zAtC0nnMC3qTeTgKU85WbDAKIloLwBAKr2u3FDgKJrJ/tAgLZtLknAq3SkOoJApLp8tQPAvf/1L8FAtyWt6oLAsGtmZUBArCArfcNAvrKhOQFAprRlZYBArWqrfcNAvvzhOQFApf7lZYBArKyrfcNAvz7hOQFApyDlpYBAu/YrfcNAv2kheQFArGqlpYBAuyerfcNAvbqhOQFAq7wlZYBAsHKtPcNAueLhOoFAoublZYBAr7StPcNAuiThOoFAqCjlZYBAsmOyeoBAp/M8MMHApPf+ccDAsaWyeoBAqDU8MMHAojn+ccDArO6yeoBAoGF8cMHAp2L+scDArCAyeoBAvrK8MMHAprR+ccDArWqyeoBAvvz8MMHApf7+ccDArKyyeoBAvz78MMHApyD+scDAu/YyeoBAv2k8cMHArGq+scDAuyeyeoBAvbq8MMHAq7w+ccDAsHK0OoBAueL8MkHAoub+ccDAr7S0OoBAuiT8MkHAqCj+ccDAoyutLYFAtWe+NQLApPfzc4EoPxLjarUG+d2w7irqPsnPlVZiPU=',
//                    'ddlTopFilter' => '-',
//                    'txtRequestId' => '',
//                    'ddlOprType' => '2',
//                    'ddlPhase' => '-1',
//                    'txtRequestName' => '',
//                    'ddlOperationType' => '-1',
//                    'ddlStatus' => '-1',
//                    'txtRequestDataSubmitedStart' => '21.01.2018 18:00',
//                    'txtRequestDataSubmitedEnd' => '22.01.2018 23:59',
//                    'ddlUser' => '-1',
//                    'ddlTypes' => 'Любой',
//                    'txtDateExecutedStart' => '',
//                    'txtDateExecutedEnd' => '',
//                    'ddlServers' => '',
//                    'txtParamLike' => '',
//                    'btnApplyFilter' => 'Выбрать',
//                ],
//                'cookies' => $cookieJar
//            ]
//        );
        $xml2 = $response1->getBody()->getContents();
        return $xml2;
    }
}
